projeto1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static #configurar arquivos statics nas urls
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
   
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

recipes/urls.py
from django.urls import path
from . import views

app_name = 'recipes'


urlpatterns = [
    path('', views.home, name='home'),
    path('recipes/category/<int:category_id>/', views.category, name='category'),
    path('recipes/<int:id>/', views.recipe, name='recipe'),
    

    #this path only accept numbers as an answer

]

recipes/models.py
from django.db import models
from django.contrib.auth.models import User

# the class is like one table in databases


class Category(models.Model):
    name = models.CharField(max_length = 65)

    def __str__(self):
        return self.name


class Recipe(models.Model):
    title = models.CharField(max_length=65)
    description = models.CharField(max_length=165)
    slug = models.SlugField()
    servings = models.IntegerField()
    servings_unit = models.CharField(max_length=65)
    preparation_time = models.IntegerField()
    preparation_time_unit = models.CharField(max_length=65)
    preparation_steps = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateField(auto_now = True)
    preparation_steps_is_html = models.BooleanField(default = False)
    is_published = models.BooleanField(default = False)
    cover = models.ImageField(upload_to='recipes/covers/%Y/%m/%d/', blank=True, default='')
    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL, null = True
    )
    author = models.ForeignKey(
        User , on_delete = models.SET_NULL, null = True
    )

    def __str__(self):
        return self.title

recipes/views.py
from django.shortcuts import render
from utils.recipes.factory import make_recipe
from .models import Recipe

def home(request):
    recipes = Recipe.objects.all().order_by('-id')
    return render(request, 'recipes/pages/home.html', context={
        'recipes':recipes,
    })

def category(request, category_id):
    recipes = Recipe.objects.filter(category__id=category_id).order_by('-id')
    return render(request, 'recipes/pages/home.html', context={
        'recipes':recipes,
    })

def recipe(request, id):
    return render(request, 'recipes/pages/recipe-view.html', context={
        'recipe':make_recipe(),
        'is_detail_page':True,
    })

recipes/templates/recipes/pages/home.html
{% extends "global/base.html" %}

{% block title %}Home |{% endblock title %}

{% block content %}
        <div class="main-content main-content-list container">
            {% for recipe in recipes %}
                {% include "recipes/partials/recipe.html" %}
            {% endfor %}
        </div>
{% endblock content %}
   

recipes/templates/recipes/pages/recipe-view.html
{% extends "global/base.html" %}

{% block title %}Alterar |{% endblock title %}

{% block content %}
        <div class="main-content main-content-detail container">
            {% include "recipes/partials/recipe.html" %}
        </div>
{% endblock content %}

recipes/templates/recipes/partials/footer.html
<footer class="main-footer">
    <div class="developer">
        <a href="https://www.linkedin.com/in/nickolas-dos-santos-cremasco-0b4118246/" target="_blank" rel="no-referrer">Nickolas Dos Santos Cremasco</a>
    </div>

    <div class="powered">
        <a href="https://www.djangoproject.com/" target="_blank" rel="no-referrer">Powered By Django</a>
    </div>
</footer>

recipes/templates/recipes/partials/head.html
{% load static %}

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!--Font Awesome-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
        integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <!--Google Fonts-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static "recipes/css/styles.css" %}">
    

recipes/templates/recipes/partials/header.html
<header class="main-header-container">
    <div class="main-header container">
        <h1>
            <!--Using name of URLs i can put it here and if a change the url it will be automating-->
            <a href="{% url "recipes:home" %}" class="main-logo">

                <i class="fa-solid fa-utensils  main-logo-icon"></i>
                <span class="main-logo-text">Recipes</span>
            </a>
        </h1>
    </div>
</header>

recipes/templates/recipes/partials/recipe.html
<div class=" recipe recipe-list-item">
    {% if recipe.cover %}
        <div class="recipe-cover">
            <a href="{% url "recipes:recipe" recipe.id %}">
                <img src="{{ recipe.cover.url }}" alt="Temporary">
            </a>
        </div>
    {% endif %}
    <div class="recipe-title-container">
        <h2 class="recipe-title">
            <a href="{% url "recipes:recipe" recipe.id %}">
            {{ recipe.title }}
            </a>
        </h2>
    </div>

    <div class="recipe-author">
        <span class="recipe-author-item">
            <i class="fa-solid fa-user"></i>
            {{recipe.author.first_name}} {{recipe.author.last_name}}
        </span>
        <span class="recipe-author-item">
            <i class="fa-solid fa-calendar-alt"></i>
            {{ recipe.created_at|date:"d/m/Y"  }} às {{recipe.created_at|date:"H:i:s"}}

        </span>
        <span class="recipe-author-item">
            <a href=" {% url 'recipes:category' recipe.category.id %}">
                <i class="fa-solid fa-layer-group"></i>
                <span>{{recipe.category.name }}</span>
            </a>

        </span>

    </div>

    <div class="recipe-content">
        <p>{{recipe.description}}</p>
    </div>

    <div class="recipe-meta-container">
        <div class="recipe-meta recipe-preparation">
            <h3 class="recipe-meta-title">
                <i class="fa-solid fa-stopwatch"></i>Preparo
            </h3>
            <div class="recipe-meta-text">
                {{recipe.preparation_time}} {{recipe.preparation_time_unit}}
                
            </div>
        </div>
        <div class="recipe-meta recipe-servings">
            <h3 class="recipe-meta-title">
                <i class="fa-solid fa-pizza-slice"></i>Porções
            </h3>
            <div class="recipe-meta-text">
                {{recipe.servings}} {{recipe.servings_unit}}
            </div>
        </div>
    </div>

    {% if is_detail_page is not True %}
        <footer class="recipe-footer">
            <a href="{% url "recipes:recipe" recipe.id %}" class="recipe-read-more button button-dark button-full-width">
                <i class="fa-solid fa-eye"></i>
                <span>Ver Mais...</span>
            </a>
            
        </footer>
    {% endif %}
        
    {% if is_detail_page is True %}
    <div class="prepariation-steps">

        {{recipe.preparation_steps|linebreaksbr}}

    </div>
    {% endif %}

    
</div>

recipes/templates/recipes/partials/search-container.html
<div class="search-container">
    <div class="container">
        <form action="" class="search-form">
            <input type="search" class="search-input" name="search">
            <button type="submit" class="search-button"><i class="fa-solid fa-magnifying-glass"></i></button>
        </form>
    </div>
</div>